 data _null_ ;
   length msgcmd $10000;
   * Send an e-mail including the pdf report as an attachment. *;
   msgcmd = 'echo "' ;
   msgcmd = trimn(msgcmd) || 'The following properties were filtered out from regression data, or failed regression:' || 
"ABECY,ABERI,ABQCA,ABQMC,ABQNM,ABQRI,AGSCH,AGSMC,ALBNY,AMMJR,AMSNT,AMSRD,ANCDT,ARRMI,ATLAB,ATLAK,ATLAN,ATLAP,ATLAW,ATLBC,ATLBD,ATLBF
,ATLBH,ATLCA,ATLCP,ATLCU,ATLDO,ATLEG,ATLEP,ATLGI,ATLGM,ATLHG,ATLJC,ATLJW,ATLKN,ATLLP,ATLMA,ATLMN,ATLMQ,ATLMS,ATLNC,ATLNL,ATLNO,ATLNP
,ATLPC,ATLPE,ATLPH,ATLPM,ATLPT,ATLRA,ATLRB,ATLRN,ATLSA,ATLSI,ATLSZ,ATLTC,ATLTN,ATLTS,ATLWS,AUAAR,AUABR,AUSAP,AUSNO,AUSSH,AVLAK,AVLBR
,BDLAP,BDLCT,BDLDT,BDLMA,BDLWD,BDRCT,BFLCH,BFLMC,BFLRI,BFLSH,BHMDW,BHMHM,BHMHV,BHMHW,BHMMC,BHMOX,BHMSC,BHXBH,BJXCY,BLKBP,BMGCY,BMGTL
,BMIMC,BNAAK,BNAAV,BNABN,BNABR,BNACA,BNACS,BNADT,BNAGI,BNAGO,BNAGV,BNAMF,BNASA,BNASH,BNATN,BOHBM,BOSAD,BOSAV,BOSBU,BOSCB,BOSCM,BOSCO
,BOSDM,BOSDN,BOSDV,BOSFB,BOSLL,BOSML,BOSNT,BOSNW,BOSPB,BOSPP,BOSPY,BOSQU,BOSST,BOSTD,BOSTT,BOSWB,BOSWE,BOSWF,BRSDT,BTRBB,BTRCH,BTRMC
,BUEAR,BUFNY,BURAP,BURRI,BVUCH,BVUDT,BWIAN,BWIAP,BWIAW,BWIBU,BWICA,BWICB,BWICL,BWIFM,BWIHU,BWIIH,BWIRA,BWIRI,BWISH,BWISS,BWRAR,CAEMH
,CAIBR,CAIEG,CAIJW,CBGHD,CHACH,CHADT,CHIAH,CHIAN,CHIAP,CHIAX,CHIBR,CHICA,CHID" ||'.' ;

 msgcmd = trimn(msgcmd) || ' The following properties had records where missing revenue plan apr values were replaced with generic ' || 
 "average values, or the default value of 200:" || 
"ABECY,ABERI,ABQCA,ABQMC,ABQNM,ABQRI,AGSCH,AGSMC,ALBNY,AMMJR,AMSNT,AMSRD,ANCDT,ARRMI,ATLAB,ATLAK,ATLAN,ATLAP,ATLAW,ATLBC,ATLBD,ATLBF" ||'.' ;
   msgcmd = trimn(msgcmd) ||'"' ;
   msgcmd = trimn(msgcmd) ||' | mail -s " EGP Regression Process, '|| "04JUN2014" ||'"';
       msgcmd = trim(left(msgcmd)) ||' '|| compress('andrew.hamilton@marriott.com');
   put msgcmd = ;
   call sysexec(msgcmd);
run;


/*
,ATLBH,ATLCA,ATLCP,ATLCU,ATLDO,ATLEG,ATLEP,ATLGI,ATLGM,ATLHG,ATLJC,ATLJW,ATLKN,ATLLP,ATLMA,ATLMN,ATLMQ,ATLMS,ATLNC,ATLNL,ATLNO,ATLNP
,ATLPC,ATLPE,ATLPH,ATLPM,ATLPT,ATLRA,ATLRB,ATLRN,ATLSA,ATLSI,ATLSZ,ATLTC,ATLTN,ATLTS,ATLWS,AUAAR,AUABR,AUSAP,AUSNO,AUSSH,AVLAK,AVLBR
,BDLAP,BDLCT,BDLDT,BDLMA,BDLWD,BDRCT,BFLCH,BFLMC,BFLRI,BFLSH,BHMDW,BHMHM,BHMHV,BHMHW,BHMMC,BHMOX,BHMSC,BHXBH,BJXCY,BLKBP,BMGCY,BMGTL
,BMIMC,BNAAK,BNAAV,BNABN,BNABR,BNACA,BNACS,BNADT,BNAGI,BNAGO,BNAGV,BNAMF,BNASA,BNASH,BNATN,BOHBM,BOSAD,BOSAV,BOSBU,BOSCB,BOSCM,BOSCO
,BOSDM,BOSDN,BOSDV,BOSFB,BOSLL,BOSML,BOSNT,BOSNW,BOSPB,BOSPP,BOSPY,BOSQU,BOSST,BOSTD,BOSTT,BOSWB,BOSWE,BOSWF,BRSDT,BTRBB,BTRCH,BTRMC
,BUEAR,BUFNY,BURAP,BURRI,BVUCH,BVUDT,BWIAN,BWIAP,BWIAW,BWIBU,BWICA,BWICB,BWICL,BWIFM,BWIHU,BWIIH,BWIRA,BWIRI,BWISH,BWISS,BWRAR,CAEMH
,CAIBR,CAIEG,CAIJW,CBGHD,CHACH,CHADT,CHIAH,CHIAN,CHIAP,CHIAX,CHIBR,CHICA,CHID

,ATLBH,ATLCA,ATLCP,ATLCU,ATLDO,ATLEG,ATLEP,ATLGI,ATLGM,ATLHG,ATLJC,ATLJW,ATLKN,ATLLP,ATLMA,ATLMN,ATLMQ,ATLMS,ATLNC,ATLNE,ATLNL,ATLNO
,ATLNP,ATLPC,ATLPE,ATLPH,ATLPT,ATLRA,ATLRB,ATLRN,ATLSA,ATLSI,ATLSZ,ATLTC,ATLTN,ATLTS,ATLWS,AUAAR,AUABR,AUSAP,AUSNO,AUSSH,AVLAK,AVLBR
,BDLAP,BDLCT,BDLDT,BDLMA,BDLWD,BDRCT,BFLCH,BFLMC,BFLRI,BFLSH,BHMDW,BHMHM,BHMHO,BHMHV,BHMHW,BHMMC,BHMOX,BHMSC,BHXBH,BJXCY,BLKBP,BMGCY
,BMGTL,BMIMC,BNAAK,BNAAV,BNABN,BNABR,BNACA,BNACS,BNADT,BNAGI,BNAGO,BNAGV,BNAMF,BNASA,BNASH,BNATN,BOHBM,BOSAD,BOSAV,BOSBU,BOSCB,BOSCM
,BOSCO,BOSDM,BOSDN,BOSDV,BOSFB,BOSLL,BOSLW,BOSML,BOSNT,BOSNW,BOSPB,BOSPP,BOSPY,BOSQU,BOSST,BOSTD,BOSTT,BOSWB,BOSWE,BOSWF,BRSDT,BRSRY
,BTRBB,BTRCH,BTRMC,BUEAR,BUFNY,BURAP,BURRI,BVUCH,BVUDT,BWIAN,BWIAP,BWIAW,BWIBU,BWICA,BWICB,BWICL,BWIFM,BWIHU,BWIIH,BWIRA,BWIRI,BWISH
,BWISS,BWIWF,BWRAR,CAEMH,CAIBR,CAIEG,CAIJW,CBGHD,CHACH,CHADT,CHIAH,CHIAN,CHIA
*/